### ISSUE TITLE
trying to download for debian.. 

### ISSUE THREAD

**Issue by takeo33** [EpicGames/ThirdParty#7] opened 2018-09-29 22:24 UTC
Hi! i'm looking forward to add you on my OAUTH account but, i'm not finding how.. Could someone give me clue?

**Comment by OrfDaBeast** [comment] 2018-09-30 16:56
Try this link to download for debian
https://wiki.unrealengine.com/Building_On_Linux

**Comment by sntdevco** [comment] 2019-04-09 08:02
@takeo33 If the issue is resolved, can you close this issue?

**Comment by emretanriverdi** [comment] 2019-10-08 00:18
@takeo33 still not closed. no need for it to be open.

**Closed** 2019-10-08 08:22 UTC
